In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/cleaned/telco_churn_cleaned.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Tenure_Group,Monthly_Charges_Group,Senior_Citizen_Status,Churn_Flag
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,Month-to-month,Yes,Electronic check,29.85,29.85,No,0-12 Months,Under $30,Non-Senior Citizen,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,One year,No,Mailed check,56.95,1889.50,No,25-48 Months,$30-$59,Non-Senior Citizen,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0-12 Months,$30-$59,Non-Senior Citizen,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,One year,No,Bank transfer (automatic),42.30,1840.75,No,25-48 Months,$30-$59,Non-Senior Citizen,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0-12 Months,$60-$89,Non-Senior Citizen,1

In [4]:
df.shape

(7043, 25)

In [5]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn',
 'Tenure_Group',
 'Monthly_Charges_Group',
 'Senior_Citizen_Status',
 'Churn_Flag']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customerID             7043 non-null   str
 1   gender                 7043 non-null   str
 2   SeniorCitizen          7043 non-null   int64
 3   Partner                7043 non-null   str
 4   Dependents             7043 non-null   str
 5   tenure                 7043 non-null   int64
 6   PhoneService           7043 non-null   str
 7   MultipleLines          7043 non-null   str
 8   InternetService        7043 non-null   str
 9   OnlineSecurity         7043 non-null   str
 10  OnlineBackup           7043 non-null   str
 11  DeviceProtection       7043 non-null   str
 12  TechSupport            7043 non-null   str
 13  StreamingTV            7043 non-null   str
 14  StreamingMovies        7043 non-null   str
 15  Contract               7043 non-null   str
 16  PaperlessBilling       7043 non-null   str
 17  PaymentMethod          7043 non-null   str
 18  MonthlyCharges         7043 non-null   float64
 19  TotalCharges           7043 non-null   str
 20  Churn                  7043 non-null   str
 21  Tenure_Group           7043 non-null   str
 22  Monthly_Charges_Group  7043 non-null   str
 23  Senior_Citizen_Status  7043 non-null   str
 24  Churn_Flag             7043 non-null   int64
dtypes: float64(1), int64(3), str(21)
memory usage: 1.3 MB

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["customerID"].duplicated().sum()

np.int64(0)

In [10]:
df["customerID"].duplicated().sum()

np.int64(0)

In [11]:
df.isnull().sum().sum()

np.int64(0)

In [15]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges   Churn_Flag
count    7043.000000  7043.000000     7043.000000   7032.000000  7043.000000
mean        0.162147    32.371149       64.761692   2283.300441     0.265370
std         0.368612    24.559481       30.090047   2266.771362     0.441561
min         0.000000     0.000000       18.250000     18.800000     0.000000
25%         0.000000     9.000000       35.500000    401.450000     0.000000
50%         0.000000    29.000000       70.350000   1397.475000     0.000000
75%         0.000000    55.000000       89.850000   3794.737500     1.000000
max         1.000000    72.000000      118.750000   8684.800000     1.000000

In [14]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [16]:
categorical_columns = [
    "gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaperlessBilling",
    "PaymentMethod",
    "Churn"
]

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts())

--- gender ---
gender
Male      3555
Female    3488
Name: count, dtype: int64

--- Partner ---
Partner
No     3641
Yes    3402
Name: count, dtype: int64

--- Dependents ---
Dependents
No     4933
Yes    2110
Name: count, dtype: int64

--- PhoneService ---
PhoneService
Yes    6361
No      682
Name: count, dtype: int64

--- MultipleLines ---
MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

--- InternetService ---
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

--- OnlineSecurity ---
OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

--- OnlineBackup ---
OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

--- DeviceProtection ---
DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

--- TechSupport ---
TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

--- StreamingTV ---
StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

--- StreamingMovies ---
StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

--- Contract ---
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

--- PaperlessBilling ---
PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

--- PaymentMethod ---
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

--- Churn ---
Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [17]:
pd.crosstab(
    df["Churn"],
    df["Churn_Flag"]
)

Churn_Flag     0     1
Churn
No          5174     0
Yes            0  1869

In [18]:
df["Tenure_Group"].value_counts()

Tenure_Group
0-12 Months     2186
25-48 Months    1594
60+ Months      1407
13-24 Months    1024
49-60 Months     832
Name: count, dtype: int64

In [19]:
tenure_order = [
    "0-12 Months",
    "13-24 Months",
    "25-48 Months",
    "49-60 Months",
    "60+ Months"
]

df["Tenure_Group"] = pd.Categorical(
    df["Tenure_Group"],
    categories=tenure_order,
    ordered=True
)

In [20]:
df["Tenure_Group"].value_counts().sort_index()

Tenure_Group
0-12 Months     2186
13-24 Months    1024
25-48 Months    1594
49-60 Months     832
60+ Months      1407
Name: count, dtype: int64

In [21]:
charge_order = [
    "Under $30",
    "$30-$59",
    "$60-$89",
    "$90+"
]

df["Monthly_Charges_Group"] = pd.Categorical(
    df["Monthly_Charges_Group"],
    categories=charge_order,
    ordered=True
)

df["Monthly_Charges_Group"].value_counts().sort_index()

Monthly_Charges_Group
Under $30    1653
$30-$59      1254
$60-$89      2392
$90+         1744
Name: count, dtype: int64

In [22]:
df[df["tenure"] == 0][
    ["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]
]

      customerID  tenure  MonthlyCharges  TotalCharges Churn
488   4472-LVYGI       0           52.55           NaN    No
753   3115-CZMZD       0           20.25           NaN    No
936   5709-LVOEQ       0           80.85           NaN    No
1082  4367-NUYAO       0           25.75           NaN    No
1340  1371-DWPAZ       0           56.05           NaN    No
3331  7644-OMVMY       0           19.85           NaN    No
3826  3213-VVOLG       0           25.35           NaN    No
4380  2520-SGTTA       0           20.00           NaN    No
5218  2923-ARZLG       0           19.70           NaN    No
6670  4075-WKNIU       0           73.35           NaN    No
6754  2775-SEFEE       0           61.90           NaN    No

In [23]:
df[df["tenure"] == 0]["TotalCharges"].value_counts()

Series([], Name: count, dtype: int64)

In [24]:
df[df["tenure"] == 0].shape

(11, 25)

In [25]:
print("Total customers:", len(df))
print("Unique customers:", df["customerID"].nunique())

Total customers: 7043
Unique customers: 7043

In [26]:
validation_summary = pd.DataFrame({
    "Metric": [
        "Total Customers",
        "Unique Customer IDs",
        "Duplicate Rows",
        "Duplicate Customer IDs",
        "Total Missing Values",
        "Total Columns"
    ],
    "Value": [
        len(df),
        df["customerID"].nunique(),
        df.duplicated().sum(),
        df["customerID"].duplicated().sum(),
        df.isnull().sum().sum(),
        df.shape[1]
    ]
})

validation_summary

                   Metric  Value
0         Total Customers   7043
1     Unique Customer IDs   7043
2          Duplicate Rows      0
3  Duplicate Customer IDs      0
4    Total Missing Values     11
5           Total Columns     25

In [27]:
print("Shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate customer IDs:", df["customerID"].duplicated().sum())
print("Missing values:", df.isnull().sum().sum())
print("Unique customers:", df["customerID"].nunique())

Shape: (7043, 25)
Duplicate rows: 0
Duplicate customer IDs: 0
Missing values: 11
Unique customers: 7043

In [28]:
df[df["TotalCharges"].isnull()][
    ["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]
]

      customerID  tenure  MonthlyCharges  TotalCharges Churn
488   4472-LVYGI       0           52.55           NaN    No
753   3115-CZMZD       0           20.25           NaN    No
936   5709-LVOEQ       0           80.85           NaN    No
1082  4367-NUYAO       0           25.75           NaN    No
1340  1371-DWPAZ       0           56.05           NaN    No
3331  7644-OMVMY       0           19.85           NaN    No
3826  3213-VVOLG       0           25.35           NaN    No
4380  2520-SGTTA       0           20.00           NaN    No
5218  2923-ARZLG       0           19.70           NaN    No
6670  4075-WKNIU       0           73.35           NaN    No
6754  2775-SEFEE       0           61.90           NaN    No

In [29]:
df["TotalCharges"].isnull().sum()

np.int64(11)

In [30]:
df["TotalCharges"] = df["TotalCharges"].fillna(0)

In [31]:
print("Missing values:", df.isnull().sum().sum())

Missing values: 0

In [32]:
df["TotalCharges"].dtype

dtype('float64')

In [33]:
df[
    ["SeniorCitizen", "tenure", "MonthlyCharges", "TotalCharges", "Churn_Flag"]
].dtypes

SeniorCitizen       int64
tenure              int64
MonthlyCharges    float64
TotalCharges      float64
Churn_Flag          int64
dtype: object

In [34]:
print("========== FINAL VALIDATION ==========")
print("Shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate customer IDs:", df["customerID"].duplicated().sum())
print("Missing values:", df.isnull().sum().sum())
print("Unique customers:", df["customerID"].nunique())
print("TotalCharges dtype:", df["TotalCharges"].dtype)

========== FINAL VALIDATION ==========
Shape: (7043, 25)
Duplicate rows: 0
Duplicate customer IDs: 0
Missing values: 0
Unique customers: 7043
TotalCharges dtype: float64

In [35]:
df.to_csv(
    "../data/cleaned/telco_churn_cleaned.csv",
    index=False
)

In [36]:
df_check = pd.read_csv("../data/cleaned/telco_churn_cleaned.csv")

print(df_check.shape)
print(df_check.isnull().sum().sum())
print(df_check["customerID"].nunique())

(7043, 25)
0
7043